### ISSUE TITLE
Library Alpha Discussion: Use Chai or Ava library for assertions?

### ISSUE THREAD

**Issue by Fleker** [actions-on-google/actions-on-google-testing-nodejs#10]
Hey AoG Devs!

Now that the alpha version of the testing library has been out for a few weeks, we'd like to get feedback on the behavior and API design of the library.

[Ava](https://github.com/avajs/ava) has built in assertions as part of its framework. Right now we use the [Chai library](http://www.chaijs.com/). If we use Ava for all assertions there are fewer dependencies. This question is primarily geared toward the example code that we will have for this library as well as tests that may appear in other samples.

**Comment by yoichiro** [comment]
I think that we should keep this library more simple. Therefore, +1 to drop the `chai` dependency. I think that users of this library have the option of whether using the `chai` or not.
