### ISSUE TITLE
Library Alpha Discussion: Should we support tests with smart home?

### ISSUE THREAD

**Issue by atulep** [actions-on-google/actions-on-google-testing-nodejs#14]
In a similar vein to testing conversational actions, should we look into extending this to smart home actions?

```
response = await assistant.send('turn on my branded light')

expect(response.status).to.be.equal('SUCCESS')
```

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
