### ISSUE TITLE
Library Alpha Discussion: Integration with the Actions Console

### ISSUE THREAD

**Issue by atulep** [actions-on-google/actions-on-google-testing-nodejs#15]
Currently, Actions Console serves as the central administrative point with your action. However, it doesn’t provide access to run your tests using AoG testing library. The current setup is to manually run tests outside of the console. Should we add an integration to Actions Console to run tests from the console?

**Comment by maaaaaaaax** [comment]
Due to more than 6 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
