### ISSUE TITLE
Library Alpha Discussion: Provide action package and get coverage results (i.e. % of intents covered in your tests)

### ISSUE THREAD

**Issue by atulep** [actions-on-google/actions-on-google-testing-nodejs#16]
Action package lists all of the intents in your project. We can potentially utilize this information to calculate coverage of intents invoked in your tests. For example, suppose your Action will contain 2 intents: A and B. If your test will look like,

```
action.startTest(‘testing happy path’, action => {
  return action.startConversation().
              then((res) => { action.send(/* some phrase to trigger intent A */) })
})
```
, then coverage output will be “50 % intents covered (½)”.

**Comment by yoichiro** [comment]
@atulep Is there a way to get a list of intents dynamically from Actions on Google? Also, how can we recognize that the intent A was triggered in the example above?

**Comment by Fleker** [comment]
I don't think there's a way to dynamically get intents, but if you pass in the action package from Dialogflow or Actions SDK, we should be able to get all intents. In the action response, you can see the intent that matches. We can track all matched intents versus all intents in general.

![image](https://user-images.githubusercontent.com/3291635/44052147-ac4e8006-9ef0-11e8-9cdf-5548eed5d80b.png)

**Comment by Fleker** [comment]
If we have a config, where you pass in your Dialogflow zip, we can grab all the ids up front by reading in the files in `intents/` (that don't end with says_*.json) to obtain the `id`

**Comment by yoichiro** [comment]
@Fleker Yes, I think that it is a simple and certain idea. Basically, this lib's users write a test code. Therefore, they can set the file path of the Dialogflow exported zip file on the test code. For example, my idea is like below:

```
const { ActionsOnGoogleAva } = require("actions-on-google-testing");
const action = new ActionsOnGoogleAva(require("./credentials.json"));

action.turnOnCoverage({
  dialogflowZipFilePath: '...'
});

action.startTest('...', action => { ... });
action.startTest('...', action => { ... });
...
```

When starting tests, that is, when the `test.before(...)` callback function called, we can load the zip file and retrieve the intents ID list. Then, when the `test.after(...)` callback function called, we can output the coverage report. These processes can be written in the `ActionsOnGoogleAva` class, I guess.

How do you think above?

**Comment by Fleker** [comment]
Yeah that's primarily what I envision. Would it make more sense to incorporate it into the constructor?

```
const action = new ActionsOnGoogleAva(require("./credentials.json", {
    actionPackage: '/path/to/dialogflow.zip'
}));
```

**Comment by Fleker** [comment]
You're correct, technically it should accept either an `actionPackage` or `dialogflowZip` parameter.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
