### ISSUE TITLE
Cannot find module 'actions-on-google-testing'

### ISSUE THREAD

**Issue by tungnh91** [actions-on-google/actions-on-google-testing-nodejs#18]
<img width="729" alt="screen shot 2018-08-20 at 5 45 28 pm" src="https://user-images.githubusercontent.com/14367240/44373994-e8aa5600-a4a0-11e8-8743-6c98aa9e1122.png">

I've followed the instruction to setup the test, and I ran into this issue. I've tried to npm install --save actions-on-google-testing but the issue remains. Is there anything else that I should do to overcome this? 

Thanks

**Comment by yoichiro** [comment]
@tungnh91 I could reproduce this situation on v0.2.0. I'm investigating this reason. Thank you for the reporting. :)

**Comment by yoichiro** [comment]
I investigated this reason. Unfortunately, the npm package of the version 0.2.0 doesn't include the `dist` directory...

![2018-08-21 11 12 13](https://user-images.githubusercontent.com/261787/44376387-47201480-a533-11e8-9f0d-ec1531fa0847.png)

@Fleker @Canain Could you re-package and re-release the version 0.2.0? Perhaps, we need to increase the version number to 0.2.1... Anyway, can you do that?

**Comment by Fleker** [comment]
Sorry for the issue. We've done a small patch. `0.2.1` should have everything inside.

Happy developing :+1:

**Comment by yoichiro** [comment]
@Fleker Thank you for the quick re-release! I just confirmed that the version 0.2.1 works.
