### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by yoichiro** [actions-on-google/actions-on-google-testing-nodejs#2]
In this current version, configurations for i18n are hardcoded. Two languages (en-US and fr-FR) are supported, but all supported language of the Google Assistant should be supported by this tool.

https://github.com/actions-on-google/actions-on-google-testing-nodejs/blob/master/actions-on-google.js#L26-L44

There are many grammars in the world. For example, unfortunately, Japanese grammar is not the same as both English and French. Especially, the invocation phrase is "talk to $APP_NAME" in English, but, in Japanese, it is "$APP_NAME につないで". That is, the position of the app name is different in the sentence.

To support all supported language, I think that we need to introduce the mechanism to construct phrases for each language.

**Comment by yoichiro** [comment]
@Fleker Could you confirm this issue and the pull request #1 as well?

**Comment by Fleker** [comment]
During the initial development I was primarily testing English actions. To verify that other locales worked I went with French. I do agree that the solution is not very scalable to all of the supported languages, so I will take a look at your pull request. Thanks.

**Comment by yoichiro** [comment]
@Fleker Do you have a plan to release the new version which is including this recently? Can I help you about the releasing?

**Comment by Fleker** [comment]
Yes we plan to release the changes soon. Last week we held off due to the US holiday break.

**Comment by Fleker** [comment]
The changes are available now :smile:

**Comment by yoichiro** [comment]
@Fleker Thank you, Nick!
