### ISSUE TITLE
how to test account linking?

### ISSUE THREAD

**Issue by ujja** [actions-on-google/actions-on-google-testing-nodejs#30]
Hi,

Is there a way to test the account linking process? (https://developers.google.com/actions/identity/google-sign-in)

As far as I know generate-credentials.js links my account to the app, so with this lib I can't test my Action with a user who is not linked yet?

(From aog simulator I can start a conversation with a user who is not linked yet.)

**Comment by ujja** [comment]
I will check something tomorrow, and update my question

**Comment by Fleker** [comment]
Unfortunately this is one feature that currently is unable to be automated.

**Comment by ujja** [comment]
UPDATE:

It is not possible to test the account linking process itself by this lib. But at least there is no error, just no response:
> Start Signin // This intent starts the Account linking in Fulfillment. User is not linked yet.
{ micOpen: false,
  textToSpeech: [],
  displayText: [],
  ssml: [],
  suggestions: [] }

And it is possible to test the conversation with linked, and not linked user.

**Comment by nathfreder** [comment]
Is it possible to test an intent that requires account linking to work?

**Comment by Fleker** [comment]
To get account linking to work, you'd need to set up account linking to the action ahead of time for the test Google account.

**Comment by nathfreder** [comment]
Thanks!
