### ISSUE TITLE
Is it possible to use ActionsOnGoogle class only?

### ISSUE THREAD

**Issue by ujja** [actions-on-google/actions-on-google-testing-nodejs#31]
Hi,

We want to integrate just ActionsOnGoogle class. (We are developing a chat testing framework Botium, and want to add GoogleActions into it, without AVA.)

If Im using it direct, I got error message "Test files must be run with the AVA CLI" and exit from node_modules/ava/lib/test-worker.js

But if I copy ActionsOnGoogle class into my project, then I'm able to use it.

Is it planned to separate ActionsOnGoogle from AVA?

Thank you!

**Comment by Fleker** [comment]
While the `ActionsOnGoogle` class is a direct implementation of the Google Assistant SDK, and can be used as such, we aren't planning a separate implementation or distribution of it in an Node.js package. But you can see how we did it, primarily loading the protobufs through gRPC.
