### ISSUE TITLE
How can i respond List item (In my mobile i click)

### ISSUE THREAD

**Issue by chandan4u** [actions-on-google/actions-on-google-testing-nodejs#33]
I'm facing issue in send request to GA, if the response is a List. It is also not displaying in response log. using google-assistent-testing library 

Through my code i'm sending response to GA `conv.ask(new List(list))`
After that it print log and  List is not displaying in response `{ micOpen: false,
  textToSpeech: [],
  displayText: [],
  ssml: [],
  suggestions: [] }`

How can i send response to action in that case?

**Comment by Fleker** [comment]
It is odd that the list data does not appear, although being unable to select a list or carousel item is a known limitation of this library.
