### ISSUE TITLE
Request: Pass through the full conv object

### ISSUE THREAD

**Issue by actionsoneverything** [actions-on-google/actions-on-google-testing-nodejs#45]
Hey,

I'm interested in testing the contents of `conv.data` in my action, could this library please support passing through the full conv object not just the client facing assistant responses please?

Thanks

**Comment by Fleker** [comment]
This library is designed for integration tests, from the perspective of an end-client. Certain details within your system are not planned to be exposed here.

**Comment by actionsoneverything** [comment]
Cool, makes sense, I'll look into testing `conv.data` contents using nodejs-dialogflow, thanks.
