### ISSUE TITLE
Issue with BasicCard containning no images

### ISSUE THREAD

**Issue by jneveux** [actions-on-google/actions-on-google-testing-nodejs#6]
Hi,

I'm using version 0.0.2. In my bot I have BasicCard which only contains text:

I get a crash here:

actions-on-google.js:183
```
imageUrl: i.basicCard.image.url,
imageAltText: i.basicCard.image.accessibilityText,
```

Would it be possible to test if the image exists?

Jean

**Comment by Fleker** [comment]
I'm working on a fix.

**Comment by Fleker** [comment]
Version 0.1.0 makes these fields optional, so your issue should be resolved.
